# Generated by Django 6.0.2 on 2026-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_sellerprofile_store_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
