# Generated by Django 6.0.3 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_image_product_price_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
