# Generated by Django 6.0.3 on 2026-03-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_productimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
